### ISSUE TITLE
How to convert to base64?

### ISSUE THREAD

**Issue by rotechcr** [Builtio-Backend/easy-excel-exporter#1]
Hello, I need some help.

How can I convert to base64? I have tried this, but no results. (The file is getting correctly created)

var downloadStream = excelAdapter.downloadFile();
var fs = require('fs');
var data = fs.readFileSync(downloadFile);
console.log(data.toString('base64'));

Thanks and regards!

**Comment by jainaman-blt** [comment]
Hey!
You should try adding a fileName and path while initializing excel-exporter. Once you call excelAdapter.downloadFile() it creates an xlsx file and returns stream. You can use file location to readFIle and convert it to base64. Please refer to code below.
`
var ExcelAdapter = require('easy-excel-exporter')
var fs = require('fs')

var excelAdapter = ExcelAdapter({
  sheetName : 'test-sheet',
  // below are path and filename which you will use to readFile
  fileName  : 'test-file', 
 // create resources folder in your working directory
  path      : './resources'
})

excelAdapter.downloadFile()
.then((stream) => {
  var data = fs.readFileSync('./resources/test-file.xlsx')
  console.log(data.toString('base64'))
})`

Cheers !

**Comment by jainaman-blt** [comment]
Hey!
You should try adding a fileName and path while initializing excel-exporter. Once you call excelAdapter.downloadFile() it creates an xlsx file and returns stream. You can use file location to readFIleSync and convert it to base64. Please refer to code below.
```
var ExcelAdapter = require('easy-excel-exporter')
var fs = require('fs')

var excelAdapter = ExcelAdapter({
  sheetName : 'test-sheet',
  // below are path and filename which you will use to read file
  fileName : 'test-file',
  // create resources folder in your working directory
  path        : './resources'
})

excelAdapter.downloadFile()
.then((stream) => {
var data = fs.readFileSync('./resources/test-file.xlsx')
console.log(data.toString('base64'))
})

```

Cheers !

**Comment by rotechcr** [comment]
Thanks a lot for your help!

It worked great. Regards!
